# LabVIEW Python Node entry point
#
# Point LabVIEW's Python Node to THIS file (not lab_instruments/src/labview_bridge.py).
# LabVIEW loads files by path without package context, so relative imports inside
# the real bridge module would fail. This shim patches sys.path first so absolute
# imports work, then re-exports every public function at module scope.
#
# LabVIEW setup:
#   Module path : <path to this repo>/labview_bridge.py
#   Function    : open_ev2300, open_psu, psu_set_voltage, ... (same names as before)

import os as _os
import sys as _sys

_repo_root = _os.path.dirname(_os.path.abspath(__file__))
if _repo_root not in _sys.path:
    _sys.path.insert(0, _repo_root)

from lab_instruments.src.labview_bridge import (  # noqa: E402
    awg_disable_all,
    awg_enable_output,
    awg_set_amplitude,
    awg_set_dc_output,
    awg_set_frequency,
    awg_set_waveform,
    close_all,
    close_instrument,
    discover_instruments,
    dmm_measure_ac_voltage,
    dmm_measure_dc_current,
    dmm_measure_dc_voltage,
    dmm_measure_diode,
    dmm_measure_frequency,
    dmm_measure_resistance_2w,
    dmm_measure_resistance_4w,
    ev2300_get_device_info,
    ev2300_read_block,
    ev2300_read_byte,
    ev2300_read_word,
    ev2300_write_block,
    ev2300_write_byte,
    ev2300_write_word,
    get_instrument_type,
    get_version,
    list_available_drivers,
    list_open_instruments,
    list_visa_resources,
    open_awg,
    open_dmm,
    open_ev2300,
    open_instrument,
    open_psu,
    open_scope,
    open_smu,
    psu_disable_all,
    psu_enable_output,
    psu_measure_current,
    psu_measure_voltage,
    psu_set_current_limit,
    psu_set_output_channel,
    psu_set_voltage,
    query_scpi,
    reset_instrument,
    scope_measure_frequency,
    scope_measure_vpp,
    scope_measure_vrms,
    scope_run,
    scope_set_timebase,
    scope_set_vertical_scale,
    scope_single,
    scope_stop,
    send_scpi,
    smu_enable_output,
    smu_measure_current,
    smu_measure_voltage,
    smu_set_current_mode,
    smu_set_voltage_mode,
)

__all__ = [
    "awg_disable_all",
    "awg_enable_output",
    "awg_set_amplitude",
    "awg_set_dc_output",
    "awg_set_frequency",
    "awg_set_waveform",
    "close_all",
    "close_instrument",
    "discover_instruments",
    "dmm_measure_ac_voltage",
    "dmm_measure_dc_current",
    "dmm_measure_dc_voltage",
    "dmm_measure_diode",
    "dmm_measure_frequency",
    "dmm_measure_resistance_2w",
    "dmm_measure_resistance_4w",
    "ev2300_get_device_info",
    "ev2300_read_block",
    "ev2300_read_byte",
    "ev2300_read_word",
    "ev2300_write_block",
    "ev2300_write_byte",
    "ev2300_write_word",
    "get_instrument_type",
    "get_version",
    "list_available_drivers",
    "list_open_instruments",
    "list_visa_resources",
    "open_awg",
    "open_dmm",
    "open_ev2300",
    "open_instrument",
    "open_psu",
    "open_scope",
    "open_smu",
    "psu_disable_all",
    "psu_enable_output",
    "psu_measure_current",
    "psu_measure_voltage",
    "psu_set_current_limit",
    "psu_set_output_channel",
    "psu_set_voltage",
    "query_scpi",
    "reset_instrument",
    "scope_measure_frequency",
    "scope_measure_vpp",
    "scope_measure_vrms",
    "scope_run",
    "scope_set_timebase",
    "scope_set_vertical_scale",
    "scope_single",
    "scope_stop",
    "send_scpi",
    "smu_enable_output",
    "smu_measure_current",
    "smu_measure_voltage",
    "smu_set_current_mode",
    "smu_set_voltage_mode",
]
